language: python
python:
  - "3.4"
  - "3.5"
  - "3.6"

# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install coveralls

before_script:
  - export PYTHONPATH=$PYTHONPATH:$(pwd)

# command to run tests
script:
  - py.test --cov=foo --cov-report=xml

after_success:
    coveralls