language: python
python: "3.6"

# command to install dependencies
install:
  - pip install -r requirements.txt

# command to run tests
script:
  - $(shell export PYTHONPATH=$PYTHONPATH:$(pwd))
  - pytest -v tests/unit_test.py