language: python
python:
  - "3.5"
  - "3.6"
  - "3.7"

# command to install dependencies
install:
  - pip install -r requirements.txt

before_script:
  - export PYTHONPATH=$PYTHONPATH:$(pwd)

# command to run tests
script:
  - pytest --cov=technews -v --cov-report term-missing tests

after_success:
    - codecov