language: python
python:
  - "2.7.16"
  - "3.6"

# command to install dependencies
install:
  - pip install -r requirements.txt

before_script:
  - export PYTHONPATH=$PYTHONPATH:$(pwd)

# command to run tests
script:
  - pytest -v tests/unit_test.py