name: Tech News Watcher

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Setup Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Test with pytest
      run: |
        pip install codecov
        pip install pytest
        pip install pytest-cov
        export PYTHONPATH=$PYTHONPATH:$(pwd)
        pytest --cov=technews -v --cov-report=xml tests
    - name: Update Code Coverage
      run: |
        codecov
